// packages/vue-app/src/App.vue
<template>
  <div class="app">
    <h1>Vue Counter</h1>
    <counter-display :count="count" />
    <counter-button :on-click-increment="handleIncrement" />
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import CounterButton from '@/components/CounterButton.vue'
import CounterDisplay from '@/components/CounterDisplay.vue'

const count = ref<number>(0)

const handleIncrement = () => {
  count.value++
}

console.log(`%cCurrent Count : ${count.value}`, 'background-color: yellow; color: black')
</script>

// packages/react-app/src/App.tsx
import { useState } from "react";
import CounterButton from "./component/CounterButton";
import CounterDisplay from "./component/CounterDisplay";

function App() {
  const [count, setCount] = useState(0);

  const handleIncrement = () => {
    setCount((prevCount) => prevCount + 1);
  };

  console.log(
    `%cCurrent Count : ${count}`,
    "background-color: yellow; color: black"
  );

  return (
    <div className="app">
      <h1>Counter</h1>
      <CounterDisplay count={count} />
      <CounterButton onIncrement={handleIncrement} />
    </div>
  );
}

export default App;
